"""
Django settings for european_champonship_kettlebell project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# --- Imports ---
import os
from pathlib import Path
from dotenv import load_dotenv

# --- Core Path Configuration ---
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = BASE_DIR.parent / '.env'
# --- Environment Variable Loading ---
# Load environment variables from .env file (should be done early)

load_dotenv(dotenv_path=dotenv_path, override=True)  # Explicitly point to .env in BASE_DIR

# --- Security Settings ---
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-placeholder-key-for-dev")  # Added a fallback for dev

# SECURITY WARNING: don't run with debug turned on in production!
# Defaulting to False is safer if DEBUG env var is not explicitly 'True'
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Define hosts/domains that are allowed to access this site.
ALLOWED_HOSTS: list[str] = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# --- Application Definition ---
INSTALLED_APPS = [
    # Jazzmin must be first
    "jazzmin",
    # Standard Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "import_export",
    # Your apps
    "live_results",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]
# CORS_ALLOWED_ORIGINS = ["https://mehardstylekettlebell.pl", "htttps://www.mehardstylekettlebell.pl",]
ROOT_URLCONF = "european_champonship_kettlebell.urls"

WSGI_APPLICATION = "european_champonship_kettlebell.wsgi.application"

# --- Templates Configuration ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],  # Consider adding a project-level templates dir
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# --- Database Configuration ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Password Validation ---
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# --- Internationalization & Localization ---
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = "pl"  # Set to Polish
TIME_ZONE = "Europe/Warsaw"
USE_I18N = True
USE_TZ = True  # Use timezone-aware datetimes

# --- Static Files Configuration ---
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = "static/"
# Directory where collectstatic will gather all static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Optional: Directories where Django will look for static files in addition to app's 'static/' dirs
# STATICFILES_DIRS = [ BASE_DIR / 'static' ]


# --- Media Files Configuration ---
# Example (Uncomment and configure if you handle user-uploaded files)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# --- Third-Party Application Settings ---

# Django REST Framework Settings (Example - add your settings here)
# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }

# Django Import Export Settings (Example - add specific settings if needed)
# IMPORT_EXPORT_USE_TRANSACTIONS = True

# Django Jazzmin Settings (Admin Theme)
# Documentation: https://django-jazzmin.readthedocs.io/en/latest/configuration.html
JAZZMIN_SETTINGS = {
    # --- General ---
    "site_title": "Admin Panel",  # Title on the login screen & html <title> tag
    "site_header": "My Company Panel",  # Title on the brand (top left)
    "site_brand": "Kettlebell Championship",  # Title on the dashboard
    "welcome_sign": "Welcome to the Kettlebell European Championship admin panel",  # Welcome text on login
    "copyright": "Kettlebell European Championship.",  # Footer copyright text
    "site_logo": None, # Logo for top left brand
    "site_logo_classes": "img-circle",  # CSS classes for the logo
    "show_ui_builder": False,  # Show UI builder for theme testing (Set True only in DEV)

    # --- Theme ---
    # Set the desired theme here. Overridden by JAZZMIN_UI_TWEAKS if 'theme' is set there.
    "theme": "lux",  # Available: "default", "cerulean", "cosmo", ..., "lux", ..., "yeti"

    # --- Top Menu ---
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"name": "Support", "url": "...", "new_window": True},
        {"model": "auth.User"},
        # {"app": "live_results"},
    ],

    # --- User Menu ---
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}  # Link to current user profile
    ],

    # --- Side Menu ---
    "show_sidebar": True,
    "navigation_expanded": False,  # Expand sidebar menu by default?
    # "hide_apps": [],
    # "hide_models": [],
    "order_with_respect_to": [  # Defines the order and grouping in the sidebar
        # 1. Authentication Section
        "auth.User",
        "auth.Group",
        # 2. Player Section
        "live_results.Player",
        # 3. Results Section
        "live_results.SnatchResult",
        "live_results.TGUResult",
        "live_results.SeeSawPressResult",
        "live_results.KBSquatResult",
        "live_results.PistolSquatResult",
        "live_results.OneKettlebellPressResult",
        "live_results.TwoKettlebellPressResult",
        # 4. Overall Results Section
        "live_results.OverallResult",
        # 5. Configuration/Basic Data Section
        "live_results.Category",
        "live_results.SportClub",
        # Add other apps here if needed
    ],
    "apps_customization": {  # Customize app labels shown in the sidebar
        "auth": {
            "label": "Authentication",
            "icon": "fas fa-users-cog",
        },
        "live_results": {
            "label": "Kettlebell Competitions",
            "icon": "fas fa-trophy",
        },
    },
    "icons": {  # Icons for specific apps and models
        # Authentication
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Kettlebell Competitions ('live_results')
        "live_results": "fas fa-trophy",
        "live_results.Player": "fas fa-user-tag",
        "live_results.Category": "fas fa-tags",
        "live_results.SportClub": "fas fa-shield-alt",
        # Results
        "live_results.SnatchResult": "fas fa-weight-hanging",
        "live_results.TGUResult": "fas fa-dumbbell",
        "live_results.SeeSawPressResult": "fas fa-balance-scale-right",
        "live_results.KBSquatResult": "fas fa-angle-double-down",
        "live_results.PistolSquatResult": "fas fa-shoe-prints",
        "live_results.OneKettlebellPressResult": "fas fa-hand-rock",
        "live_results.TwoKettlebellPressResult": "fas fa-hands",
        # Summary
        "live_results.OverallResult": "fas fa-clipboard-list",
    },
    "default_icon_parents": "fas fa-hands",  # Default icon for apps
    "default_icon_children": "fas fa-circle",  # Default icon for models

    # --- Change View / Forms ---
    "changeform_format": "horizontal_tabs",  # Options: single, horizontal_tabs, vertical_tabs, collapsible, carousel
    # "changeform_format_overrides": {"auth.user": "collapsible"},
    "related_modal_active": True,  # Use modals for related object popups

    # --- Custom Assets ---
    "custom_css": None,  # Path to custom CSS file
    "custom_js": None,  # Path to custom JS file
}

# Optional Jazzmin UI Tweaks (Overrides JAZZMIN_SETTINGS for specific UI elements)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",  # e.g., navbar-primary, navbar-dark
    "accent": "accent-primary",  # e.g., accent-primary, accent-warning
    "navbar": "navbar-dark navbar-primary",  # CSS classes for top navbar
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",  # CSS classes for sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    # "theme": "lux", # Commented out: Theme conflict resolved in JAZZMIN_SETTINGS above. Only set here if you *specifically* want to override the main setting.
    "dark_mode_theme": None,  # Theme used when dark mode is active
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True  # Make admin actions sticky
}

# --- Custom Project Settings ---
# Add any custom settings specific to your project here
# EXAMPLE_SETTING = "example_value"
